- title: true
- shields:
    style: 'flat-square'
    shields:
      - alt: 'Mateu Aguiló Bosch (e0ipso)'
        image: 'badge/♥-e0ipso-green.svg'
        link: 'https://mateuaguilo.com/'
      - alt: 'Travis'
        image: 'travis/e0ipso/plugnplay.svg'
        link: 'https://travis-ci.org/e0ipso/plugnplay/'
      - alt: Coverage Status
        image: 'coveralls/github/e0ipso/plugnplay/master.svg'
        link: 'https://coveralls.io/github/e0ipso/plugnplay?branch=master'
      - alt: Last Commit
        image: 'github/last-commit/e0ipso/plugnplay.svg'
        link: 'https://github.com/e0ipso/plugnplay'
      - alt: David Dependency Management
        image: 'david/e0ipso/plugnplay.svg'
        link: 'https://david-dm.org/e0ipso/plugnplay'
      - alt: 'Node'
        image: 'node/v/plugnplay.svg'
        link: 'http://npmjs.com/package/plugnplay'
- include: './docs/summary.md'
- include: './docs/quick.md'
- include: './docs/faq.md'
- include: './docs/plugins.md'
- include: './docs/options.md'
- contributors: true
- license: true
