language: node_js
notifications:
  email: false
node_js:
  - '6'
  - '8'
  - '10'
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
    - .tmp
    - ~/.npm
before_install:
  - git fetch origin --tags
  - npm install --global npm@5
  - npm install --global greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - npm test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  # Report coverage to coveralls.io
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
